export const rootActionTypes = {
  USER: {
    FETCH_REQUEST: "FETCH_USER_REQUEST",
    FETCH_SUCCESS: "FETCH_USER_SUCCESS",
    FETCH_FAILURE: "FETCH_USER_FAILURE",
    UNAUTHORIZED: "UNAUTHORIZED",
    CHANGE_CURRENT_ROLE: "USER_CHANGE_CURRENT_ROLE",
    RESET_CURRENT_ROLE: "USER_RESET_CURRENT_ROLE"
  },
  ALLOWED_LIFE_USERS: {
    FETCH_REQUEST: "FETCH_ALLOWED_LIFE_USERS_REQUEST",
    FETCH_SUCCESS: "FETCH_ALLOWED_LIFE_USERS_SUCCESS",
    FETCH_FAILURE: "FETCH_ALLOWED_LIFE_USERS_FAILURE"
  },
  WINDOW_RESIZED: "WINDOW_RESIZED",
  SET_GLOBAL_BLOCKING_MESSAGE: "SET_GLOBAL_BLOCKING_MESSAGE",
  TOASTR_MESSAGE: {
    SUCCESS: "TOASTR_MESSAGE_SUCCESS",
    ERROR: "TOASTR_MESSAGE_ERROR",
    COUNTDOWN: "TOASTR_MESSAGE_COUNTDOWN"
  },
  SET_ADMIN_CONTAINER_HEIGHT: "SET_ADMIN_CONTAINER_HEIGHT",
  SET_MANAGE_CARD_STATE: "SET_MANAGE_CARD_STATE"
};
