export const categoryActionTypes = {
  CATEGORIES: {
    FETCH_REQUEST: "FETCH_CATEGORIES_REQUEST",
    FETCH_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
    FETCH_FAILURE: "FETCH_CATEGORIES_FAILURE",
    SET_OR_TOGGLE_SORT: "CATEGORIES_SET_OR_TOGGLE_SORT",
    SET_SEARCH_FILTER_VAL: "CATEGORIES_SET_SEARCH_FILTER_VAL"
  },
  CATEGORY: {
    ADD: "CATEGORY_ADD",
    ADD_SUCCESS: "CATEGORY_ADD_SUCCESS",
    ADD_FAILURE: "CATEGORY_ADD_FAILURE",
    SELECT: "CATEGORY_SELECT",
    DESELECT: "CATEGORY_DESELECT",
    SET_QUICK_ACTION_ID: "CATEGORY_SET_QUICK_ACTION_ID",
    OPTIMISTIC_FIELD_CHANGE: "CATEGORY_OPTIMISTIC_FIELD_CHANGE",
    RECEIVE_UPDATE: "CATEGORY_RECEIVE_UPDATE",
    UPDATE_ERROR: "CATEGORY_UPDATE_ERROR",
    UPDATE_PERMISSIONS_SUCCESS: "CATEGORY_UPDATE_PERMISSIONS_SUCCESS",
    UPDATE_PERMISSIONS_FAILURE: "CATEGORY_UPDATE_PERMISSIONS_FAILURE"
  }
};
